// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.
//
// Find the next triangle number that is also pentagonal and hexagonal.

function triangle(n) {
  return n * (n + 1) / 2;
}

function isTriangle(k) {
  // just do reverse of equation
  var n = (-1 + Math.sqrt(8 * k + 1))
  return n % 2 == 0 ? n / 2 : false;
}


function pentagonal(n) {
  return n * (3 * n - 1) / 2;
}

function isPentagonal(k) {
  // just do reverse of equation
  var n = (1 + Math.sqrt(24 * k + 1))
  return n % 6 == 0 ? n / 6 : false;
}


function hexagonal(n) {
  return n * (2 * n - 1);
}

function isHexagonal(k) {
  // just do reverse of equation
  var n = (1 + Math.sqrt(8 * k + 1))
  return n % 4 == 0 ? n / 4 : false;
}

function findNum(starting) {
  var i = starting;

  while(true) {
    var tri = triangle(i);
    if(isPentagonal(tri) && isHexagonal(tri)) return tri;
    i++;
  }
}


console.log("Solution is", findNum(286));
